### PR TITLE
[KAOS-1344] Expose nested containers api

### PR DESCRIPTION
**Pull request by Burbaka**
@lampapos @Vandalko please review

https://keyprprojects.atlassian.net/browse/KAOS-1344

### CODE REVIEW

**Comment by Vandalko** [comment]
any info how this gonna be used ?

**Comment by Burbaka** [comment]
@Vandalko It will allows not to return `renderer` in pair instance and query all Placemarks right inside it
https://github.com/Keypr/kaos-map/pull/65/files#r65560794

Now I'm returning renderer just to save later information about placemarks in it.

**Comment by Vandalko** [comment]
pls consolidate with @lampapos to fix  the build

**Comment by Burbaka** [comment]
@Vandalko I'm doing PR in his branch. And in his PR he fixes the build.

**Pull request merged**
