### PR TITLE
Add resource prefix and fix integration with AS

### PR DESCRIPTION
**Pull request by Vandalko**
Fixes:
- https://github.com/googlemaps/android-maps-utils/issues/259
- https://github.com/googlemaps/android-maps-utils/issues/252

### CODE REVIEW

**Comment by roman-mazur** [comment]
:+1:

**Comment by roman-mazur** [comment]
@Vandalko I switched on travis integration. Could you amend the last commit without changes and force push it? Or update the branch in a different way.

**Comment by roman-mazur** [comment]
:+1: what about downgrading gradle plugin to older beta so that we get it finally merged into the upstream?

**Comment by Vandalko** [comment]
original PR to upstream was merged

**Comment by roman-mazur** [comment]
Awesome!

**Pull request merged**
